name: charts_flutter
version: 0.12.0
publish_to: none

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  charts_common:
    path: ../../packages/charts_common
  collection: ^1.14.5
  flutter:
    sdk: flutter
  intl: ^0.19.0
  logging: ^1.0.2
  meta: ^1.1.1


dev_dependencies:
  mockito: ^5.0.0
  #  build_runner: ^1.11.0
  flutter_test:
    sdk: flutter
  test: ^1.3.0